const BUTTON_OPTIONS = [
  { value: 'l4', label: 'L4' },
  { value: 'r4', label: 'R4' },
  { value: 't1', label: 'T1' },
  { value: 't2', label: 'T2' },
  { value: 't3', label: 'T3' },
  { value: 'c1', label: 'C1' },
  { value: 'c2', label: 'C2' },
  { value: 'c3', label: 'C3' },
  { value: 'c4', label: 'C4' },
  { value: 'a', label: 'A' },
  { value: 'b', label: 'B' },
  { value: 'x', label: 'X' },
  { value: 'y', label: 'Y' },
  { value: 'lb', label: 'LB' },
  { value: 'rb', label: 'RB' },
  { value: 'lt', label: 'LT' },
  { value: 'rt', label: 'RT' },
  { value: 'l3', label: 'L3' },
  { value: 'r3', label: 'R3' },
  { value: 'back', label: 'Back' },
  { value: 'start', label: 'Start' },
  { value: 'dpad_up', label: 'DPad Up' },
  { value: 'dpad_down', label: 'DPad Down' },
  { value: 'dpad_left', label: 'DPad Left' },
  { value: 'dpad_right', label: 'DPad Right' },
  { value: 'screenshot', label: 'Screenshot' },
];

export { BUTTON_OPTIONS };
